/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/test/dialog': RouteRecordInfo<'/test/dialog', '/test/dialog', Record<never, never>, Record<never, never>>,
    '/test/locales': RouteRecordInfo<'/test/locales', '/test/locales', Record<never, never>, Record<never, never>>,
    '/test/moment': RouteRecordInfo<'/test/moment', '/test/moment', Record<never, never>, Record<never, never>>,
    '/test/stores': RouteRecordInfo<'/test/stores', '/test/stores', Record<never, never>, Record<never, never>>,
  }
}
