
package io.u2ware.ocpp.v2_1.model;

import javax.annotation.processing.Generated;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;

@JsonInclude(JsonInclude.Include.ALWAYS)
@SuperBuilder
@ToString
@Getter
@Accessors(fluent = true)
@NoArgsConstructor
@AllArgsConstructor
@JsonPropertyOrder({
    "receiptUrl",
    "receiptId",
    "customData"
})
@Generated("jsonschema2pojo")
public class NotifySettlementResponse {

    /**
     * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
     * 
     * 
     * 
     */
    @JsonProperty("receiptUrl")
    @JsonPropertyDescription("The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.\r\n\r\n")
    @Size(max = 2000)
    private String receiptUrl;
    /**
     * The receipt id if the receipt is generated by CSMS.
     * 
     * 
     * 
     */
    @JsonProperty("receiptId")
    @JsonPropertyDescription("The receipt id if the receipt is generated by CSMS.\r\n\r\n")
    @Size(max = 50)
    private String receiptId;
    /**
     * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
     * 
     */
    @JsonProperty("customData")
    @JsonPropertyDescription("This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.")
    @Valid
    private CustomData customData;

}
